### PR TITLE
Update README.promisc

### PR DESCRIPTION
**Pull request by morphyno**
minor updates to the readme, a big thank you for adding this feature!

### CODE REVIEW

**Comment by aabc** [comment]
Hi, Why `destination=127.0.0.1:2055` if this is default argument?

**Comment by morphyno** [comment]
sorry, i just took that part from standard README

**Comment by aabc** [comment]
IC. I think `modprobe` step is not needed at all, since, after `depmod` xptables will autoload appropriate module when you add rule with `-j NETFLOW`.

**Comment by morphyno** [comment]
agreed

**Comment by aabc** [comment]
I completely forgot that `make install` automatically issuing `depmod`.

**Pull request merged**
