### PR TITLE
Cross compilling

### PR DESCRIPTION
**Pull request by alex-eri**
Will check real compilatior if specified instead of system.

https://github.com/aabc/ipt-netflow/issues/39#issuecomment-280674420

### CODE REVIEW

**Comment by ZackMattor** [comment]
Is this ready to be tested? I'll try it out.

**Comment by alex-eri** [comment]
I removed /usr/include dir and get error as yours. This fixes testing includes.

**Comment by ZackMattor** [comment]
It compiles fine, but it seems to install the libs in `/lib/xtables` and not `/usr/lib/iptables` i'm going to try doing a clean build.

**Comment by aabc** [comment]
I handled it a bit differently, w/o running `which`.

**Pull request closed without merging**
