### PR TITLE
Linux 5.0 support

### PR DESCRIPTION
**Pull request by mhcerri**
Fixes for Linux 5.0-rc5.

### CODE REVIEW

**Comment by xtaran** [comment]
This very likely fixes #108, thanks!

**Comment by aabc** [comment]
Thanks. It seems, that this patch breaks compatibility with older kernels, which I want to remain. So, I should rework it before applying.

**Comment by xtaran** [comment]
> Thanks. It seems, that this patch breaks compatibility with older kernels, which I want to remain. So, I should rework it before applying.

Back to which kernel version do you care? Thadeu, who wrote the patches, told me on IRC, he might be able to provide an according patch set, but only back to 3.13 or so, not further.

**Comment by aabc** [comment]
@xtaran I want to retain compatibility back to the Centos 6, if possible. Thanks.

**Comment by xtaran** [comment]
> I want to retain compatibility back to the Centos 6, if possible. Thanks.

I don't know what kernel version CentOS 6 runs, but given that RHEL 6 uses (a heavily modified) 2.6.32 kernel, I assume that CentOS 6 uses the same or a very similar kernel version.

**Comment by mhcerri** [comment]
I just updated my branch with the changes that Thadeu did to address those issues.

**Comment by aabc** [comment]
Thanks. I try to make compat code for a older api, getting new kernel improvements into main code when possible. So, in this case, I would switch code to using `ktime_get_real_ts64`, but implement `ktime_get_real_ts64` for older kernel in compat. But, I don't insist you do it.

I hope you are not hurrying. I will take some time to check if it compiles/works on all required kernel versions.

**Comment by aabc** [comment]
FYI: I closed/reopened PR to trigger Travis build.

**Comment by aabc** [comment]
Patch merged. Thank you.

**Pull request merged**
