### PR TITLE
tcp options: fix possible shift-out-of-bounds

### PR DESCRIPTION
**Pull request by vvfedorenko**
Calculation of tcp option bit is done before actual check and could lead to shift-out-of-bounds error tracked by UBSAN. Fix it by checking for zero value before the calculation.

Signed-off-by: Vadim Fedorenko <vvfedorenko@github.com>

### CODE REVIEW

**Comment by aabc** [comment]
Thanks for the fix.
It seems that bit counting in this code was also incorrect.
```
                        ret |= 1 << (32 - opt);
```
It should be based on `31` not `32`. So that bit `0` shall correspond to a left-most bit `31`. 

```
[5.8.8](https://www.rfc-editor.org/rfc/rfc5102.html#section-5.8.8).  tcpOptions

   Description:
      TCP options in packets of this Flow.  The information is encoded
      in a set of bit fields.  For each TCP option, there is a bit in
      this set.  The bit is set to 1 if any observed packet of this Flow
      contains the corresponding TCP option.  Otherwise, if no observed
      packet of this Flow contained the respective TCP option, the value
      of the corresponding bit is 0.
      Options are mapped to bits according to their option numbers.
      Option number X is mapped to bit X.  TCP option numbers are
      maintained by IANA.

              0     1     2     3     4     5     6     7
          +-----+-----+-----+-----+-----+-----+-----+-----+
          |   0 |   1 |   2 |   3 |   4 |   5 |   6 |   7 |  ...
          +-----+-----+-----+-----+-----+-----+-----+-----+

              8     9    10    11    12    13    14    15
          +-----+-----+-----+-----+-----+-----+-----+-----+
      ... |   8 |   9 |  10 |  11 |  12 |  13 |  14 |  15 |...
          +-----+-----+-----+-----+-----+-----+-----+-----+

             16    17    18    19    20    21    22    23
          +-----+-----+-----+-----+-----+-----+-----+-----+
      ... |  16 |  17 |  18 |  19 |  20 |  21 |  22 |  23 |...
          +-----+-----+-----+-----+-----+-----+-----+-----+
```

**Comment by aabc** [comment]
I'm also curious who is running production kernel with UBSAN enabled?

**Comment by vvfedorenko** [comment]
Hmm, looks like you are right. I'll update PR.

Usually UBSAN is used to run tests, and it's a good idea to build all modules for test kernel

**Comment by vvfedorenko** [comment]
And about ip4_options code - it looks a little bit ugly, but safe because of options table.
But what is the reason for this bit-shift games? Why don't simply use `hton()`? Right now the code assumes that it's running on the arch which has endianess different to network order. Otherwise it will break the network order of bits in the IPFIX field

**Comment by aabc** [comment]
Bit-shift games are because we need to sent bit which corresponds to an option number (not just pass number into it directly).

Also, bit numbering is implemented from **incorrect** RFC 5102 https://www.rfc-editor.org/rfc/rfc5102.html#section-5.8.5 which defines numbers as messed up table. To fix this we could (perhaps should) simplify the code and just convert ipv4 option _number_ to a bit shift.

**Comment by aabc** [comment]
> To fix this we could (perhaps should) simplify the code and just convert ipv4 option number to a bit shift.

- At the times of RFC 5102 (in 2008) they numbered **bits** in 'network order' with leftmost bit of leftmost byte being highest bit. Thus they number bits from 0 down to 31. (Thus we reverse bit order.)
```
           0      1      2      3      4      5      6      7
       +------+------+------+------+------+------+------+------+
       | EOOL | NOP  | SEC  | LSR  |  TS  |E-SEC |CIPSO |  RR  | ...
       +------+------+------+------+------+------+------+------+
```
`EOOL` is number `0` and thus it's most significant (highest) bit of most significant (leftmost) byte.

- After Errata 1737 (in 2009), they (without much explanations) seems to assume common bit numbering per byte — most significant bit in byte is 7, thus they revert diagram to correct things but actually to mess it even more because they forgot about byte order.
```
           0      1      2      3      4      5      6      7
       +------+------+------+------+------+------+------+------+
       |  RR  |CIPSO |E-SEC |  TS  | LSR  | SEC  | NOP  | EOOL | ...
       +------+------+------+------+------+------+------+------+
```
`EOOL` become most significant (highest) bit of first byte (and i seems to be just sequence on bytes, not 32-bit number).

- After years they notice this and did another Errata 2944 (in 2011):
```
          24     25     26     27     28     29     30     31
       +------+------+------+------+------+------+------+------+
   ... |  RR  |CIPSO |E-SEC |  TS  | LSR  | SEC  | NOP  | EOOL |
       +------+------+------+------+------+------+------+------+
```
Now again `EOOL` is most significant bit of 32-bit `ipv4Options` qword. When 32-bit number encoded in network order it will become leftmost bit of leftmost byte.

**Comment by aabc** [comment]
@vvfedorenko Will you also simplify and fix `ip4_options`, or I can do it myself later.

**Comment by vvfedorenko** [comment]
Let's keep this PR as simple fix of shift-out-of-bounds.
I'm not pretty familiar with the documents you mentioned above and it will take time to me to understand changes fully.
With that said feel free to implement changes in ip4_options yourself

**Comment by aabc** [comment]
Thanks you!

**Comment by aabc** [comment]
I also fixed your commit (in follow-up commits), you may wish to review.

**Pull request merged**
