### PR TITLE
Set the correct port for collector.

### LINKED ISSUE #111: port destination not applied
```bash
cat /proc/net/stat/ipt_netflow
ipt_NETFLOW 2.3-5-g940c61a
sock0: 192.168.0.4:2055
sock1: 192.168.0.40:2055
sock2: 192.168.0.12:2055
sock3: 192.168.0.43:9996
```
modules load
```bash
options ipt_NETFLOW  destination=192.168.0.4:9996,192.168.0.40:9996,192.168.0.12:9996,192.168.0.43:9996 inactive_timeout=10 active_timeout=15 sndbuf=65000
```
в sysctl -a | grep netflow
```bash
net.netflow.destination = 192.168.0.4:9996,192.168.0.40:9996,192.168.0.12:9996,192.168.0.43:9996
```

dmesg
```bash
[63634.738848] ipt_NETFLOW: added destination 192.168.0.4:2055
[63634.738856] ipt_NETFLOW: added destination 192.168.0.40:2055
[63634.738878] ipt_NETFLOW: added destination 192.168.0.12:2055
[63634.738884] ipt_NETFLOW: added destination 192.168.0.43:9996
```

### PR DESCRIPTION
**Pull request by dbugnar**
Fix #111 
kstrtoul string parameter must be null terminated.

### CODE REVIEW

**Comment by aabc** [comment]
Thanks. But this taking more and more complicated. Maybe you can take different approach - just implement function with semantics of old `simple_strtoul` (similar to what is done in `arch/x86/boot/string.c`) and insert it in place of old `simple_strtoul` instead of hacking in this unsuitable `kstrtoul`, which additional `strcspn`, and additional `strcpy`, and additional static buffer, and `strcmp` with empty string(?), just to avoid `simple_strtoul` which is still have a log uses in the kernel:

```
linux$ git grep simple_strtoul | wc -l
762
```

**Comment by dbugnar** [comment]
I guess this is what you suggest.

**Comment by aabc** [comment]
That looks better. Please, put this `strtoul` into the end of `compat.h`. Also, please remove `#if LINUX_VERSION_CODE ... KERNEL_VERSION(3,2,0)` and just always use provided `strtoul`. Thanks.

**Comment by aabc** [comment]
Thanks. Just merged your commits.

I don't understand the intent of your original fix, though. Obsoleted does not mean deprecated.

**Pull request merged**
