### PR TITLE
natevents: optimize export

### PR DESCRIPTION
**Pull request by junjunk**
* Use export list to minimize spinlock pressure
* Use conntrack time start/stop
* Use kzalloc() instead of memset()

### CODE REVIEW

**Comment by aabc** [comment]
1. "All checks have failed" can you fix this?
2. Can you split this into thee patches with each feature separately?

**Comment by junjunk** [comment]
I've made separate patches
Failed checks of compilation seems very strange to me, because I use Ubuntu 16.04 LTS to make this patch and it compiles and works very well on it

**Comment by junjunk** [comment]
It seems to me I found what was broken on CentOS 7 kernels.
But the diagnostic from Travis-ci seems to be broken. The real problem on CentOS 7 was

> [junk@noc ipt-netflow]$ make
> Compiling for kernel 3.10.0-957.5.1.el7.x86_64
> make -C /lib/modules/3.10.0-957.5.1.el7.x86_64/build M=/home/junk/src/ipt-netflow modules CONFIG_DEBUG_INFO=y
> make[1]: Entering directory `/usr/src/kernels/3.10.0-957.5.1.el7.x86_64'
>   CC [M]  /home/junk/src/ipt-netflow/ipt_NETFLOW.o
> /home/junk/src/ipt-netflow/ipt_NETFLOW.c: In function ‘netflow_conntrack_event’:
> /home/junk/src/ipt-netflow/ipt_NETFLOW.c:4606:18: error: incompatible types when assigning to type ‘ktime_t’ from type ‘u_int64_t’
>     nel->ts_ktime = tstamp->stop;
>                   ^
> /home/junk/src/ipt-netflow/ipt_NETFLOW.c:4613:18: error: incompatible types when assigning to type ‘ktime_t’ from type ‘u_int64_t’
>     nel->ts_ktime = tstamp->start;
>                   ^
> /home/junk/src/ipt-netflow/ipt_NETFLOW.c:4616:6: error: wrong type argument to unary exclamation mark
>   if (!nel->ts_ktime)
>       ^
> make[2]: *** [/home/junk/src/ipt-netflow/ipt_NETFLOW.o] Error 1
> make[1]: *** [_module_/home/junk/src/ipt-netflow] Error 2
> make[1]: Leaving directory `/usr/src/kernels/3.10.0-957.5.1.el7.x86_64'
> make: *** [ipt_NETFLOW.ko] Error 2
>

**Comment by junjunk** [comment]
Hmm. the problem with 'xt_in' exists in CentOS 7.8, kernel-devel-3.10.1062 (and updates). But CentOS 7.7 uses different version, as I mentioned before - kernel-devel-3.10.957 (and updates).
It seems to me that Travis CI Docker containers for CentOS 7 have updated version of kernel-devel, independently of CentOS minor version.
So, the problem is with compilation of current version on CentOS 7.8, and it does not depend on my pull request, should be fixed in different PR

**Comment by aabc** [comment]
IC. I need to fix that before accepting your PR.

**Comment by aabc** [comment]
I fixed that centos issue. Btw, `nat_list_export` doesn't need to be global.

**Comment by junjunk** [comment]
Sure, will make it local.
Also, how do you think, is it better to move nat events counters to per cpu stats structure ?

**Comment by aabc** [comment]
1. Can you squash `natevents: make nat_list_export local` with `natevents: use export list`
2. I think nat events are infrequent enough and so that would be useless micro-optimization only complicating the code.

**Comment by junjunk** [comment]
Well, in my case with 4+Mpps, 2M conntracks and short timers nat events are really frequent. Some times its about 10+k events per second. I have about 10Mbps of netflow traffic with only nat events in such case

**Comment by junjunk** [comment]
squashed to commits in one

**Comment by aabc** [comment]
All applied, thanks.

**Comment by aabc** [comment]
> Well, in my case with 4+Mpps, 2M conntracks and short timers nat events are really frequent. Some times its about 10+k events per second. I have about 10Mbps of netflow traffic with only nat events in such case

You may test per cpu stats if it really gives any benefit. Please show performance numbers in such case.

**Pull request merged**
