### PR TITLE
Replace simple_strtoul with kstrtoul, since simple_strtoul is obsolete.

### PR DESCRIPTION
**Pull request by dbugnar**

### CODE REVIEW

**Comment by aabc** [comment]
Thanks, but this breaks compatibility with older kernels.

**Comment by dbugnar** [comment]
With 3.2 kernel version, the function was set as obsolete. I can add the changes just if the kernel version is bigger or equal than 3.2

**Comment by aabc** [comment]
If you going to do it, make it like this - 1. change code to use `kstrtoul`; 2. if kernel version is below 3.2 make shim from `kstrtoul` to `simple_strtoul` (so it works on older kernels), 2. if kernel version is equal or above 3.2 do nothing.

**Comment by dbugnar** [comment]
I updated this PR, I hope I followed your steps.

**Comment by aabc** [comment]
Thanks!

**Pull request merged**
